### ISSUE TITLE
ng2-webstorage is not working for Angular 7.1

### ISSUE THREAD

**Issue by klmuralimohan** [PillowPillow/ng2-webstorage#112]
**Versions (please complete the following information):**
 - NgxWebstorage: [e.g. 4.0.x]
 - Angular: [e.g. 7.1.0]

**Describe the bug**
This NgxWebstorage 4.0.1 is not working in Angular 7.1. Getting the following errors after integrated the package.

ngx-webstorage.js:396 Uncaught TypeError: Object(...) is not a function
    at ngx-webstorage.js:396
    at Module../node_modules/ngx-webstorage/fesm5/ngx-webstorage.js (ngx-webstorage.js:398)
    at __webpack_require__ (bootstrap:83)
    at Module../src/app/app.module.ts (app.component.ts:10)
    at __webpack_require__ (bootstrap:83)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:83)
    at Object.0 (main.ts:4)
    at __webpack_require__ (bootstrap:83)
    at checkDeferredModules (bootstrap:45)
(anonymous) @ ngx-webstorage.js:396
./node_modules/ngx-webstorage/fesm5/ngx-webstorage.js @ ngx-webstorage.js:398
__webpack_require__ @ bootstrap:83
./src/app/app.module.ts @ app.component.ts:10
__webpack_require__ @ bootstrap:83
./src/main.ts @ main.ts:1
__webpack_require__ @ bootstrap:83
0 @ main.ts:4
__webpack_require__ @ bootstrap:83
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.js:1
client:148 [WDS] Warnings while compiling.
warnings @ client:148
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone.js:1332
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
client:154 ./node_modules/ngx-webstorage/fesm5/ngx-webstorage.js 396:62-80
"export 'ɵɵdefineInjectable' was not found in '@angular/core'
warnings @ client:154
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone.js:1332
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
client:154 ./node_modules/ngx-webstorage/fesm5/ngx-webstorage.js 1058:55-73
"export 'ɵɵdefineInjectable' was not found in '@angular/core'
warnings @ client:154
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone.js:1332
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770
client:154 ./node_modules/ngx-webstorage/fesm5/ngx-webstorage.js 1058:145-153
"export 'ɵɵinject' was not found in '@angular/core'
warnings @ client:154
onmessage @ socket.js:41
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone.js:1332
push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
invokeTask @ zone.js:1744
globalZoneAwareCallback @ zone.js:1770

**Comment by PillowPillow** [comment]
Hello, the v4.x doesn't support angular 7, please use the v3.x

From wiki : 
https://github.com/PillowPillow/ng2-webstorage/wiki

Choose the version corresponding to your Angular version:

 [Angular](https://angular.io)     | ngx-webstorage
 ----------- | -------------------
 8           | 4.x+   
 7           | 3.x+               
 5,6         | 2.x
